version: '3'

services:
  web:
    build: .
    image: hw2:latest

    ports:
      - '5000:5000'
    environment:
      DB_HOST: database
      DB_USER_NAME: asivkov
      DB_USER_PASSWORD: password
      DB_NAME: dwh

  database:

    image: 'postgres:latest'

    expose:
      - "5432"
    environment:
      POSTGRES_USER: asivkov
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dwh
